### ISSUE TITLE
Adding more functionality to the texteditor

### ISSUE THREAD

**Issue by lordblendi** [big-data-europe/ember-stack-builder-frontend#1]
- tab functionality to text editor
- the editor should resize depending on it's content. check, why is it not working properly on load

**Comment by fr0gs** [comment]
@lordblendi @asjongers I am not sure if  this is the repository, perhaps you are referring to https://github.com/big-data-europe/ember-swarm-ui-engine since this one is afaik discontinued.

**Comment by lordblendi** [comment]
More like https://github.com/big-data-europe/ember-stack-builder-engine, but thanks, I'll remove this
